### ISSUE TITLE
Deno Deploy后导出书籍报错

### ISSUE THREAD

**Issue by colin4k** [champkeh/wereadx#20]
**详细描述一下遇到的问题**
导出书籍到最后，提示错误，看了下Deno的错误日志如下，是因为DATABASE_URL变量设置错误码？我看了另一个Issue，目前是建立了这个变量但是没赋值
ConnectionRefused: Connection refused (os error 111)
    at async Object.connect (ext:deno_net/01_net.js:474:55)
    at cachedError (https://deno.land/x/postgresjs@v3.3.5/src/query.js:171:23)
    at new Query (https://deno.land/x/postgresjs@v3.3.5/src/query.js:36:24)
    at sql (https://deno.land/x/postgresjs@v3.3.5/src/index.js:112:11)
    at createTable (file:///src/src/database/download.ts:8:14)

**期望的结果**

**书籍BookID**
如果涉及到特定书籍，请提供书籍的 bookId

**Comment by champkeh** [comment]
刚推了一版，把它改成可选的了哈哈

**Comment by colin4k** [comment]
好的，我再试试

**Comment by colin4k** [comment]
> 刚推了一版，把它改成可选的了哈哈

按照新增的DATABASE_URL的设置说明，配置好了Supabase数据库，现在已经ok了，感谢！
